language: node_js
node_js:
- '8'
dist: trusty
sudo: required
addons:
  chrome: stable
  postgresql: '10'
  apt:
    packages:
    - autoconf
    - bison
    - build-essential
    - file
    - g++
    - gcc
    - imagemagick
    - libffi-dev
    - libgdbm-dev
    - libgdbm3
    - libicu-dev
    - libidn11-dev
    - libncurses5-dev
    - libpq-dev
    - libprotobuf-dev
    - libreadline6-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libyaml-dev
    - pkg-config nodejs
    - postgresql-10
    - postgresql-client-10
    - postgresql-contrib-10
    - protobuf-compiler
    - redis-server
    - redis-tools
    - zlib1g-dev
before_install:
- npm install -g greenkeeper-lockfile@1
- "./bin/setup-mastodon-in-travis.sh"
before_script:
- npm run lint
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
install:
- npm ci || npm i
script: travis_retry npm run $COMMAND
env:
  global:
  - PGPORT=5433
  - secure: iR11lD+OAyTJdNoK67esDOrd34HKQboJo0DrVL4xqwoAwQGmNX7posBtcj0TOwVAdHfd5S80xlhWlMebrtHWR9oMtdcBXusWnehZVRB0WE89n8enkJCbAxn5uMpcEpKpDHTcfR/Gbxf2sw15dTy0PrW/ldiZXWf7wybJEBGbrEP7QI8oy3VHzmKpSyjRpN/hnSlgxskVnfIMKPp43D+705Ka7aMJNTWZ5dAdKdIjQWX6j6jlqx6Vl+qIq7td3DTZA9A5ft8HxaWC27F1bbd52PdRY2h8Ii3Ps+n8Q8uZK1KJPp9t3pPk+PmYINu2715ArukRk73kahnFadBQLhytn95FLiyKOLj+ajBNo+o3KIQDs3qRj8gkXpkJpuLAPgwABOEVWuLh9y+oa33IDYVzyESRVtXqbbwgziYVjNQCozP1Nt9+Wyh4YHfdOjEEMdlVlkwlyzPfaLAqVBusEphnaF/vx7itdVvxOMQYNcSRoBrAgciN4ng0GZHi5P85DMXnNV41r+d3JK5JEYZD/gpSja5cPUlpPlkXsKiElG3fEoO2D/Uc8rR9Cu84XiJiJQjP91QuWagfdhgqM4YOndt2YukiGzRzDMjTx1BzSW4S11RQGWzZrv06zmDLXTlnUAMEm1/Exo4L6VfgRvyFmgM0LAT+IceVEHbOKC/Hnd8Y3mo=
  - secure: E9t4zTDdPX9I4XgeC5zJEy+mIM2s0MFPpNfJ/mc5q/JX+gQkHSNkE/32NKgfSce85v33kWWxiPK4qorgX4B+v/MkK6kVQ2HSC7p4XttlQucvSICh/hYSM21WnH7g7DRNj3mDWHWEAwQuquaxVLfGWL60M/svnKG9MOoewos9iDj9AvANm6J09DjRmLuqmDV+VL+cV6ZL/SvUZ5Ervkgs/s3nXHEMse9rKMH/6/KncTGGPRolqyx86XSU6/XtRKX2+bEdiOaIxUYYvjcHJZTKxpSelPpEHjoUfWCM2CG3WyjtYkLF/1Romh8Ft4pnz+iiTzN3eWaT2ralOFvW30oB3cKbDcFb6LDGfXYw7v+XIORc79Ehcb2XlweEymf7fPhbx+7bkCfudRCMLw6OUWXoh66BBjOh2gcQYQ2+3U8KV7YKl/ZQHYb722wE6rN0YvJ6zGriWomDuV1smdyu4teo4lY2oVUUUGflyz2HWxnjVbqWizw4k69TNIcEEQ8j8YgdXMUxNMUOJoCu0c3Lnd8J1BeU/7LX87c54/oCMjEivnsENGIC/EUgAoXDi3L0y7HzHgaDs112p5zjspJsSSON/T4E2uyyb2RpjBY4Ghl43a/RDAlv1gUFtvbanphg3PEGMfG7B2gxk9Z/v5J9pUP/NtsspmT2MvTHZXtH/44XPEU=
  - secure: vVjNqP/lB02TF0jssuuJTdpa/glb9Do6a0Fb2/d10PyciQteRINGW/HJSPJ/8d2bZRLki1nKNhnxDwzY8vHm1d4bM7kYN1PjwwEBbpPveaGkqEfbqduaYM6FhmiUz8nPnaU9NsEqwjkNLKH4n1u7AOKKH1OBaGq/akcPTZ9xgtUZDQ5FZQ7WB9k8S2jF7htI6lqFCTie/CAWBLK2OtTDg6wnEdtM7TEdF0PmtUCQGkG5rYTCtZlYbozNH4I+1Z0JB3KXKPdftPEl36UOhFMHk3lmyhCNyeGaTho8/cfEWaPJMF8pIkCDK386FCrn9qs1nvoEj0EtHqdlxzNrN7jPvsaLPwEe8V1ADySf15gcdc2Nz6ALbaz7FbPoUI7jGIK1yg/f28ZtF/nVCwdRTJ5GdI0FVI2IKyidi5dXthR9n2t0imQbHU0ajophMw9B62MWDK3xKERCB9ekD7z775B01iRKkrZewzUrB5L0ITbXkI6RIzpvgu469gVd9Gt4B5ywK4TAA+LJa7QHVmI/KX4cgIJgxaCftwFfZiVl1m2vgMLVyEedRDgrDrPgnmUcWWAM4Rq7MYAvVpy5e/6NijqA/PvtxCeGz1QylarRK8gUSvkS8eLS3trOXz3X8Bbi6YSsS/7oKbZPHRrVmIhqtG0Auhlr2gi7gA9iGXSw3yXQ+Fc=
  - secure: M/8ck2ktSkIAG7Zqy5/Uq3heHC0issm5X+ifhKxF79tUc1+t43/m5xm0ZLhY9pt3kCf+hVEh6UoD2EK0lIBwxat/kuOGKXCyewmMgyrD+FvENJSyvNPRWX96r5O7qFK0DFGWuViS3+cbtz40GnA7DCxo41/Gtne5HVHn3R46ZFhDvdbWGkdtBxGG/vaU1Y9vUphjLhG3H+ZOaYiHwtDH3DBGCywsWFWsA98Q8VZYUlIdwWluQ4MeWy8a0nFpX39i5uF2fweQR3wBZJu8nlP+s8i2w6I9qUXFpMJYGahBZV3OKgyFjPW6wCebi2odrXQGNyIrSUrKKsYIPEvyZkCFOemS6a/k6ZKxtxe9i98Tcmfe3obrGSG8Y8pp1bdymWjaQ1JZPtIMbXZJjVEuKcRJkyg4GOW47BTNu7m1d1H0wDWL6LI/6dYwl/KhwjP3VVRAltjocklLKYrnxGRdaKCZaW893mKVGXAnDOdMSipnOHaDOgnwiHu3mrr0YwRmJpLoDfeNF/Tr8BNZ7hWBGxLF9wpAh6wz8ZpCxTv3F8ehqLU6Ieo64Wnhtrmm65LUGW7a4ZlbJJLl/zoDCZBR82kQzK+n1mbWSCgA1E3g+sBHeFGkjgXjS7vCVMFA21wVtOQhYzQRQg/ZznocYvVdXOf3Xal/My1zx/7fM82D5oQ4FPY=
matrix:
  include:
  - env: BROWSER=chrome:headless COMMAND=test-browser-suite0
  - env: BROWSER=chrome:headless COMMAND=test-browser-suite1
  - env: COMMAND=test-unit
  - env: COMMAND=deploy-all-travis
  - env: COMMAND=test-lighthouse-ci
  allow_failures:
  - env: COMMAND=deploy-all-travis
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
cache:
  npm: true
  yarn: true
  bundler: true
  directories:
  - "/home/travis/.rvm/"
  - "/home/travis/ffmpeg-static/"
